version: '3.8'

services:
  postgres:
    container_name: curso_programacao_postgres
    image: postgres
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=curso_programacao